// flow-typed signature: 39710c1536e812965864ce06cb6b7a35
// flow-typed version: <<STUB>>/redux-actions_v^2.6.4/flow_v0.102.0-rc

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-actions'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-actions' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-actions/dist/redux-actions' {
  declare module.exports: any;
}

declare module 'redux-actions/dist/redux-actions.min' {
  declare module.exports: any;
}

declare module 'redux-actions/es/combineActions' {
  declare module.exports: any;
}

declare module 'redux-actions/es/constants' {
  declare module.exports: any;
}

declare module 'redux-actions/es/createAction' {
  declare module.exports: any;
}

declare module 'redux-actions/es/createActions' {
  declare module.exports: any;
}

declare module 'redux-actions/es/createCurriedAction' {
  declare module.exports: any;
}

declare module 'redux-actions/es/handleAction' {
  declare module.exports: any;
}

declare module 'redux-actions/es/handleActions' {
  declare module.exports: any;
}

declare module 'redux-actions/es/index' {
  declare module.exports: any;
}

declare module 'redux-actions/es/utils/arrayToObject' {
  declare module.exports: any;
}

declare module 'redux-actions/es/utils/camelCase' {
  declare module.exports: any;
}

declare module 'redux-actions/es/utils/flattenActionMap' {
  declare module.exports: any;
}

declare module 'redux-actions/es/utils/flattenReducerMap' {
  declare module.exports: any;
}

declare module 'redux-actions/es/utils/flattenWhenNode' {
  declare module.exports: any;
}

declare module 'redux-actions/es/utils/get' {
  declare module.exports: any;
}

declare module 'redux-actions/es/utils/getLastElement' {
  declare module.exports: any;
}

declare module 'redux-actions/es/utils/hasGeneratorInterface' {
  declare module.exports: any;
}

declare module 'redux-actions/es/utils/identity' {
  declare module.exports: any;
}

declare module 'redux-actions/es/utils/isArray' {
  declare module.exports: any;
}

declare module 'redux-actions/es/utils/isEmpty' {
  declare module.exports: any;
}

declare module 'redux-actions/es/utils/isFunction' {
  declare module.exports: any;
}

declare module 'redux-actions/es/utils/isMap' {
  declare module.exports: any;
}

declare module 'redux-actions/es/utils/isNil' {
  declare module.exports: any;
}

declare module 'redux-actions/es/utils/isNull' {
  declare module.exports: any;
}

declare module 'redux-actions/es/utils/isPlainObject' {
  declare module.exports: any;
}

declare module 'redux-actions/es/utils/isString' {
  declare module.exports: any;
}

declare module 'redux-actions/es/utils/isSymbol' {
  declare module.exports: any;
}

declare module 'redux-actions/es/utils/isUndefined' {
  declare module.exports: any;
}

declare module 'redux-actions/es/utils/ownKeys' {
  declare module.exports: any;
}

declare module 'redux-actions/es/utils/toString' {
  declare module.exports: any;
}

declare module 'redux-actions/es/utils/unflattenActionCreators' {
  declare module.exports: any;
}

declare module 'redux-actions/lib/combineActions' {
  declare module.exports: any;
}

declare module 'redux-actions/lib/constants' {
  declare module.exports: any;
}

declare module 'redux-actions/lib/createAction' {
  declare module.exports: any;
}

declare module 'redux-actions/lib/createActions' {
  declare module.exports: any;
}

declare module 'redux-actions/lib/createCurriedAction' {
  declare module.exports: any;
}

declare module 'redux-actions/lib/handleAction' {
  declare module.exports: any;
}

declare module 'redux-actions/lib/handleActions' {
  declare module.exports: any;
}

declare module 'redux-actions/lib/index' {
  declare module.exports: any;
}

declare module 'redux-actions/lib/utils/arrayToObject' {
  declare module.exports: any;
}

declare module 'redux-actions/lib/utils/camelCase' {
  declare module.exports: any;
}

declare module 'redux-actions/lib/utils/flattenActionMap' {
  declare module.exports: any;
}

declare module 'redux-actions/lib/utils/flattenReducerMap' {
  declare module.exports: any;
}

declare module 'redux-actions/lib/utils/flattenWhenNode' {
  declare module.exports: any;
}

declare module 'redux-actions/lib/utils/get' {
  declare module.exports: any;
}

declare module 'redux-actions/lib/utils/getLastElement' {
  declare module.exports: any;
}

declare module 'redux-actions/lib/utils/hasGeneratorInterface' {
  declare module.exports: any;
}

declare module 'redux-actions/lib/utils/identity' {
  declare module.exports: any;
}

declare module 'redux-actions/lib/utils/isArray' {
  declare module.exports: any;
}

declare module 'redux-actions/lib/utils/isEmpty' {
  declare module.exports: any;
}

declare module 'redux-actions/lib/utils/isFunction' {
  declare module.exports: any;
}

declare module 'redux-actions/lib/utils/isMap' {
  declare module.exports: any;
}

declare module 'redux-actions/lib/utils/isNil' {
  declare module.exports: any;
}

declare module 'redux-actions/lib/utils/isNull' {
  declare module.exports: any;
}

declare module 'redux-actions/lib/utils/isPlainObject' {
  declare module.exports: any;
}

declare module 'redux-actions/lib/utils/isString' {
  declare module.exports: any;
}

declare module 'redux-actions/lib/utils/isSymbol' {
  declare module.exports: any;
}

declare module 'redux-actions/lib/utils/isUndefined' {
  declare module.exports: any;
}

declare module 'redux-actions/lib/utils/ownKeys' {
  declare module.exports: any;
}

declare module 'redux-actions/lib/utils/toString' {
  declare module.exports: any;
}

declare module 'redux-actions/lib/utils/unflattenActionCreators' {
  declare module.exports: any;
}

declare module 'redux-actions/src/combineActions' {
  declare module.exports: any;
}

declare module 'redux-actions/src/constants' {
  declare module.exports: any;
}

declare module 'redux-actions/src/createAction' {
  declare module.exports: any;
}

declare module 'redux-actions/src/createActions' {
  declare module.exports: any;
}

declare module 'redux-actions/src/createCurriedAction' {
  declare module.exports: any;
}

declare module 'redux-actions/src/handleAction' {
  declare module.exports: any;
}

declare module 'redux-actions/src/handleActions' {
  declare module.exports: any;
}

declare module 'redux-actions/src/index' {
  declare module.exports: any;
}

declare module 'redux-actions/src/utils/arrayToObject' {
  declare module.exports: any;
}

declare module 'redux-actions/src/utils/camelCase' {
  declare module.exports: any;
}

declare module 'redux-actions/src/utils/flattenActionMap' {
  declare module.exports: any;
}

declare module 'redux-actions/src/utils/flattenReducerMap' {
  declare module.exports: any;
}

declare module 'redux-actions/src/utils/flattenWhenNode' {
  declare module.exports: any;
}

declare module 'redux-actions/src/utils/get' {
  declare module.exports: any;
}

declare module 'redux-actions/src/utils/getLastElement' {
  declare module.exports: any;
}

declare module 'redux-actions/src/utils/hasGeneratorInterface' {
  declare module.exports: any;
}

declare module 'redux-actions/src/utils/identity' {
  declare module.exports: any;
}

declare module 'redux-actions/src/utils/isArray' {
  declare module.exports: any;
}

declare module 'redux-actions/src/utils/isEmpty' {
  declare module.exports: any;
}

declare module 'redux-actions/src/utils/isFunction' {
  declare module.exports: any;
}

declare module 'redux-actions/src/utils/isMap' {
  declare module.exports: any;
}

declare module 'redux-actions/src/utils/isNil' {
  declare module.exports: any;
}

declare module 'redux-actions/src/utils/isNull' {
  declare module.exports: any;
}

declare module 'redux-actions/src/utils/isPlainObject' {
  declare module.exports: any;
}

declare module 'redux-actions/src/utils/isString' {
  declare module.exports: any;
}

declare module 'redux-actions/src/utils/isSymbol' {
  declare module.exports: any;
}

declare module 'redux-actions/src/utils/isUndefined' {
  declare module.exports: any;
}

declare module 'redux-actions/src/utils/ownKeys' {
  declare module.exports: any;
}

declare module 'redux-actions/src/utils/toString' {
  declare module.exports: any;
}

declare module 'redux-actions/src/utils/unflattenActionCreators' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-actions/dist/redux-actions.js' {
  declare module.exports: $Exports<'redux-actions/dist/redux-actions'>;
}
declare module 'redux-actions/dist/redux-actions.min.js' {
  declare module.exports: $Exports<'redux-actions/dist/redux-actions.min'>;
}
declare module 'redux-actions/es/combineActions.js' {
  declare module.exports: $Exports<'redux-actions/es/combineActions'>;
}
declare module 'redux-actions/es/constants.js' {
  declare module.exports: $Exports<'redux-actions/es/constants'>;
}
declare module 'redux-actions/es/createAction.js' {
  declare module.exports: $Exports<'redux-actions/es/createAction'>;
}
declare module 'redux-actions/es/createActions.js' {
  declare module.exports: $Exports<'redux-actions/es/createActions'>;
}
declare module 'redux-actions/es/createCurriedAction.js' {
  declare module.exports: $Exports<'redux-actions/es/createCurriedAction'>;
}
declare module 'redux-actions/es/handleAction.js' {
  declare module.exports: $Exports<'redux-actions/es/handleAction'>;
}
declare module 'redux-actions/es/handleActions.js' {
  declare module.exports: $Exports<'redux-actions/es/handleActions'>;
}
declare module 'redux-actions/es/index.js' {
  declare module.exports: $Exports<'redux-actions/es/index'>;
}
declare module 'redux-actions/es/utils/arrayToObject.js' {
  declare module.exports: $Exports<'redux-actions/es/utils/arrayToObject'>;
}
declare module 'redux-actions/es/utils/camelCase.js' {
  declare module.exports: $Exports<'redux-actions/es/utils/camelCase'>;
}
declare module 'redux-actions/es/utils/flattenActionMap.js' {
  declare module.exports: $Exports<'redux-actions/es/utils/flattenActionMap'>;
}
declare module 'redux-actions/es/utils/flattenReducerMap.js' {
  declare module.exports: $Exports<'redux-actions/es/utils/flattenReducerMap'>;
}
declare module 'redux-actions/es/utils/flattenWhenNode.js' {
  declare module.exports: $Exports<'redux-actions/es/utils/flattenWhenNode'>;
}
declare module 'redux-actions/es/utils/get.js' {
  declare module.exports: $Exports<'redux-actions/es/utils/get'>;
}
declare module 'redux-actions/es/utils/getLastElement.js' {
  declare module.exports: $Exports<'redux-actions/es/utils/getLastElement'>;
}
declare module 'redux-actions/es/utils/hasGeneratorInterface.js' {
  declare module.exports: $Exports<'redux-actions/es/utils/hasGeneratorInterface'>;
}
declare module 'redux-actions/es/utils/identity.js' {
  declare module.exports: $Exports<'redux-actions/es/utils/identity'>;
}
declare module 'redux-actions/es/utils/isArray.js' {
  declare module.exports: $Exports<'redux-actions/es/utils/isArray'>;
}
declare module 'redux-actions/es/utils/isEmpty.js' {
  declare module.exports: $Exports<'redux-actions/es/utils/isEmpty'>;
}
declare module 'redux-actions/es/utils/isFunction.js' {
  declare module.exports: $Exports<'redux-actions/es/utils/isFunction'>;
}
declare module 'redux-actions/es/utils/isMap.js' {
  declare module.exports: $Exports<'redux-actions/es/utils/isMap'>;
}
declare module 'redux-actions/es/utils/isNil.js' {
  declare module.exports: $Exports<'redux-actions/es/utils/isNil'>;
}
declare module 'redux-actions/es/utils/isNull.js' {
  declare module.exports: $Exports<'redux-actions/es/utils/isNull'>;
}
declare module 'redux-actions/es/utils/isPlainObject.js' {
  declare module.exports: $Exports<'redux-actions/es/utils/isPlainObject'>;
}
declare module 'redux-actions/es/utils/isString.js' {
  declare module.exports: $Exports<'redux-actions/es/utils/isString'>;
}
declare module 'redux-actions/es/utils/isSymbol.js' {
  declare module.exports: $Exports<'redux-actions/es/utils/isSymbol'>;
}
declare module 'redux-actions/es/utils/isUndefined.js' {
  declare module.exports: $Exports<'redux-actions/es/utils/isUndefined'>;
}
declare module 'redux-actions/es/utils/ownKeys.js' {
  declare module.exports: $Exports<'redux-actions/es/utils/ownKeys'>;
}
declare module 'redux-actions/es/utils/toString.js' {
  declare module.exports: $Exports<'redux-actions/es/utils/toString'>;
}
declare module 'redux-actions/es/utils/unflattenActionCreators.js' {
  declare module.exports: $Exports<'redux-actions/es/utils/unflattenActionCreators'>;
}
declare module 'redux-actions/lib/combineActions.js' {
  declare module.exports: $Exports<'redux-actions/lib/combineActions'>;
}
declare module 'redux-actions/lib/constants.js' {
  declare module.exports: $Exports<'redux-actions/lib/constants'>;
}
declare module 'redux-actions/lib/createAction.js' {
  declare module.exports: $Exports<'redux-actions/lib/createAction'>;
}
declare module 'redux-actions/lib/createActions.js' {
  declare module.exports: $Exports<'redux-actions/lib/createActions'>;
}
declare module 'redux-actions/lib/createCurriedAction.js' {
  declare module.exports: $Exports<'redux-actions/lib/createCurriedAction'>;
}
declare module 'redux-actions/lib/handleAction.js' {
  declare module.exports: $Exports<'redux-actions/lib/handleAction'>;
}
declare module 'redux-actions/lib/handleActions.js' {
  declare module.exports: $Exports<'redux-actions/lib/handleActions'>;
}
declare module 'redux-actions/lib/index.js' {
  declare module.exports: $Exports<'redux-actions/lib/index'>;
}
declare module 'redux-actions/lib/utils/arrayToObject.js' {
  declare module.exports: $Exports<'redux-actions/lib/utils/arrayToObject'>;
}
declare module 'redux-actions/lib/utils/camelCase.js' {
  declare module.exports: $Exports<'redux-actions/lib/utils/camelCase'>;
}
declare module 'redux-actions/lib/utils/flattenActionMap.js' {
  declare module.exports: $Exports<'redux-actions/lib/utils/flattenActionMap'>;
}
declare module 'redux-actions/lib/utils/flattenReducerMap.js' {
  declare module.exports: $Exports<'redux-actions/lib/utils/flattenReducerMap'>;
}
declare module 'redux-actions/lib/utils/flattenWhenNode.js' {
  declare module.exports: $Exports<'redux-actions/lib/utils/flattenWhenNode'>;
}
declare module 'redux-actions/lib/utils/get.js' {
  declare module.exports: $Exports<'redux-actions/lib/utils/get'>;
}
declare module 'redux-actions/lib/utils/getLastElement.js' {
  declare module.exports: $Exports<'redux-actions/lib/utils/getLastElement'>;
}
declare module 'redux-actions/lib/utils/hasGeneratorInterface.js' {
  declare module.exports: $Exports<'redux-actions/lib/utils/hasGeneratorInterface'>;
}
declare module 'redux-actions/lib/utils/identity.js' {
  declare module.exports: $Exports<'redux-actions/lib/utils/identity'>;
}
declare module 'redux-actions/lib/utils/isArray.js' {
  declare module.exports: $Exports<'redux-actions/lib/utils/isArray'>;
}
declare module 'redux-actions/lib/utils/isEmpty.js' {
  declare module.exports: $Exports<'redux-actions/lib/utils/isEmpty'>;
}
declare module 'redux-actions/lib/utils/isFunction.js' {
  declare module.exports: $Exports<'redux-actions/lib/utils/isFunction'>;
}
declare module 'redux-actions/lib/utils/isMap.js' {
  declare module.exports: $Exports<'redux-actions/lib/utils/isMap'>;
}
declare module 'redux-actions/lib/utils/isNil.js' {
  declare module.exports: $Exports<'redux-actions/lib/utils/isNil'>;
}
declare module 'redux-actions/lib/utils/isNull.js' {
  declare module.exports: $Exports<'redux-actions/lib/utils/isNull'>;
}
declare module 'redux-actions/lib/utils/isPlainObject.js' {
  declare module.exports: $Exports<'redux-actions/lib/utils/isPlainObject'>;
}
declare module 'redux-actions/lib/utils/isString.js' {
  declare module.exports: $Exports<'redux-actions/lib/utils/isString'>;
}
declare module 'redux-actions/lib/utils/isSymbol.js' {
  declare module.exports: $Exports<'redux-actions/lib/utils/isSymbol'>;
}
declare module 'redux-actions/lib/utils/isUndefined.js' {
  declare module.exports: $Exports<'redux-actions/lib/utils/isUndefined'>;
}
declare module 'redux-actions/lib/utils/ownKeys.js' {
  declare module.exports: $Exports<'redux-actions/lib/utils/ownKeys'>;
}
declare module 'redux-actions/lib/utils/toString.js' {
  declare module.exports: $Exports<'redux-actions/lib/utils/toString'>;
}
declare module 'redux-actions/lib/utils/unflattenActionCreators.js' {
  declare module.exports: $Exports<'redux-actions/lib/utils/unflattenActionCreators'>;
}
declare module 'redux-actions/src/combineActions.js' {
  declare module.exports: $Exports<'redux-actions/src/combineActions'>;
}
declare module 'redux-actions/src/constants.js' {
  declare module.exports: $Exports<'redux-actions/src/constants'>;
}
declare module 'redux-actions/src/createAction.js' {
  declare module.exports: $Exports<'redux-actions/src/createAction'>;
}
declare module 'redux-actions/src/createActions.js' {
  declare module.exports: $Exports<'redux-actions/src/createActions'>;
}
declare module 'redux-actions/src/createCurriedAction.js' {
  declare module.exports: $Exports<'redux-actions/src/createCurriedAction'>;
}
declare module 'redux-actions/src/handleAction.js' {
  declare module.exports: $Exports<'redux-actions/src/handleAction'>;
}
declare module 'redux-actions/src/handleActions.js' {
  declare module.exports: $Exports<'redux-actions/src/handleActions'>;
}
declare module 'redux-actions/src/index.js' {
  declare module.exports: $Exports<'redux-actions/src/index'>;
}
declare module 'redux-actions/src/utils/arrayToObject.js' {
  declare module.exports: $Exports<'redux-actions/src/utils/arrayToObject'>;
}
declare module 'redux-actions/src/utils/camelCase.js' {
  declare module.exports: $Exports<'redux-actions/src/utils/camelCase'>;
}
declare module 'redux-actions/src/utils/flattenActionMap.js' {
  declare module.exports: $Exports<'redux-actions/src/utils/flattenActionMap'>;
}
declare module 'redux-actions/src/utils/flattenReducerMap.js' {
  declare module.exports: $Exports<'redux-actions/src/utils/flattenReducerMap'>;
}
declare module 'redux-actions/src/utils/flattenWhenNode.js' {
  declare module.exports: $Exports<'redux-actions/src/utils/flattenWhenNode'>;
}
declare module 'redux-actions/src/utils/get.js' {
  declare module.exports: $Exports<'redux-actions/src/utils/get'>;
}
declare module 'redux-actions/src/utils/getLastElement.js' {
  declare module.exports: $Exports<'redux-actions/src/utils/getLastElement'>;
}
declare module 'redux-actions/src/utils/hasGeneratorInterface.js' {
  declare module.exports: $Exports<'redux-actions/src/utils/hasGeneratorInterface'>;
}
declare module 'redux-actions/src/utils/identity.js' {
  declare module.exports: $Exports<'redux-actions/src/utils/identity'>;
}
declare module 'redux-actions/src/utils/isArray.js' {
  declare module.exports: $Exports<'redux-actions/src/utils/isArray'>;
}
declare module 'redux-actions/src/utils/isEmpty.js' {
  declare module.exports: $Exports<'redux-actions/src/utils/isEmpty'>;
}
declare module 'redux-actions/src/utils/isFunction.js' {
  declare module.exports: $Exports<'redux-actions/src/utils/isFunction'>;
}
declare module 'redux-actions/src/utils/isMap.js' {
  declare module.exports: $Exports<'redux-actions/src/utils/isMap'>;
}
declare module 'redux-actions/src/utils/isNil.js' {
  declare module.exports: $Exports<'redux-actions/src/utils/isNil'>;
}
declare module 'redux-actions/src/utils/isNull.js' {
  declare module.exports: $Exports<'redux-actions/src/utils/isNull'>;
}
declare module 'redux-actions/src/utils/isPlainObject.js' {
  declare module.exports: $Exports<'redux-actions/src/utils/isPlainObject'>;
}
declare module 'redux-actions/src/utils/isString.js' {
  declare module.exports: $Exports<'redux-actions/src/utils/isString'>;
}
declare module 'redux-actions/src/utils/isSymbol.js' {
  declare module.exports: $Exports<'redux-actions/src/utils/isSymbol'>;
}
declare module 'redux-actions/src/utils/isUndefined.js' {
  declare module.exports: $Exports<'redux-actions/src/utils/isUndefined'>;
}
declare module 'redux-actions/src/utils/ownKeys.js' {
  declare module.exports: $Exports<'redux-actions/src/utils/ownKeys'>;
}
declare module 'redux-actions/src/utils/toString.js' {
  declare module.exports: $Exports<'redux-actions/src/utils/toString'>;
}
declare module 'redux-actions/src/utils/unflattenActionCreators.js' {
  declare module.exports: $Exports<'redux-actions/src/utils/unflattenActionCreators'>;
}
