// flow-typed signature: b676ec71026db3481ceee83c809ccd08
// flow-typed version: <<STUB>>/redux-promise_v^0.6.0/flow_v0.117.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-promise'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-promise' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-promise/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-promise/lib/index' {
  declare module.exports: $Exports<'redux-promise/lib'>;
}
declare module 'redux-promise/lib/index.js' {
  declare module.exports: $Exports<'redux-promise/lib'>;
}
